In [1]:
import numpy as np
import torch
torch.__version__

'1.11.0'

张量创建

In [2]:
#创建一个 5x3 矩阵, 但是未初始化:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
#创建一个随机初始化的矩阵
x = torch.rand(5, 3)
print(x)

tensor([[0.5796, 0.8784, 0.3566],
        [0.7350, 0.1009, 0.1527],
        [0.1309, 0.0381, 0.6233],
        [0.2941, 0.8908, 0.0080],
        [0.3784, 0.8582, 0.5701]])


In [4]:
#创建一个0填充的矩阵，数据类型为long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#创建tensor并使用现有数据初始化
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
#根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)
x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      # 对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0442,  1.3674, -0.5634],
        [ 1.5626, -0.2803, -0.7353],
        [ 0.2444,  0.4526,  0.3748],
        [ 0.1930,  0.2592,  1.4515],
        [ 1.1604, -0.9145, -1.4865]])


In [7]:
#torch.Size返回值是tuple类型, 所以它支持tuple类型的所有操作.
print(x.size())

torch.Size([5, 3])


张量加法

In [8]:
#加法
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

#存储到result中
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0408,  1.9265, -0.2419],
        [ 2.3911,  0.2804,  0.2050],
        [ 1.2027,  1.4071,  1.0704],
        [ 0.2648,  0.8517,  2.1122],
        [ 2.0573, -0.4159, -1.2183]])
tensor([[-0.0408,  1.9265, -0.2419],
        [ 2.3911,  0.2804,  0.2050],
        [ 1.2027,  1.4071,  1.0704],
        [ 0.2648,  0.8517,  2.1122],
        [ 2.0573, -0.4159, -1.2183]])
tensor([[-0.0408,  1.9265, -0.2419],
        [ 2.3911,  0.2804,  0.2050],
        [ 1.2027,  1.4071,  1.0704],
        [ 0.2648,  0.8517,  2.1122],
        [ 2.0573, -0.4159, -1.2183]])


In [9]:
#替换
# adds x to y
y.add_(x)
print(y)
#任何以_结尾的操作都会用结果替换原变量，例如x.copy_(y)，x.t_()，都会改变x

tensor([[-0.0408,  1.9265, -0.2419],
        [ 2.3911,  0.2804,  0.2050],
        [ 1.2027,  1.4071,  1.0704],
        [ 0.2648,  0.8517,  2.1122],
        [ 2.0573, -0.4159, -1.2183]])


张量维度

In [10]:
#张量索引
print(x[:, 1])

tensor([ 1.3674, -0.2803,  0.4526,  0.2592, -0.9145])


In [11]:
#改变维度
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1：从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
#读取张量元素值
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2122])
-1.2122035026550293


numpy与tensor互转

In [13]:
#tensor转numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#观察a和b的值如何转变
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
#numpy转tensor
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
#观察a和b的值如何转变
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


移动tensor

In [15]:
#cpu和gpu互相转换
a = torch.ones(2,3)
print(a.type())
print(a)
if torch.cuda.is_available():
    b = a.cuda()
    print(b.type())
    print(b)
    
    print(b.cpu())
    print(b.cpu().type())
    
else:
    print("无可用的cuda")

torch.FloatTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])
无可用的cuda


In [16]:
#,to移动到任何设备
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改
else:
    print("无可用的cuda")

无可用的cuda
