In [1]:
import numpy as np
import torch
torch.__version__

'1.1.0'

张量创建

In [2]:
#创建一个 5x3 矩阵, 但是未初始化:
x = torch.empty(5, 3)
print(x)

tensor([[9.3674e-39, 1.0929e-38, 1.0469e-38],
        [8.4490e-39, 1.0102e-38, 9.0919e-39],
        [1.0102e-38, 8.9082e-39, 8.4489e-39],
        [1.0102e-38, 1.0561e-38, 1.0286e-38],
        [1.0653e-38, 1.0469e-38, 9.5510e-39]])


In [3]:
#创建一个随机初始化的矩阵
x = torch.rand(5, 3)
print(x)

tensor([[0.5355, 0.0090, 0.4239],
        [0.2559, 0.1107, 0.1981],
        [0.5081, 0.1923, 0.2689],
        [0.5087, 0.8546, 0.7561],
        [0.1393, 0.3418, 0.8746]])


In [4]:
#创建一个0填充的矩阵，数据类型为long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#创建tensor并使用现有数据初始化
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
#根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)
x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      # 对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.6021e-01, -1.2667e+00,  7.6505e-02],
        [ 4.0681e-01,  5.8928e-01,  2.9419e+00],
        [ 3.9013e-01, -1.0448e+00, -1.7985e-03],
        [ 4.4175e-01, -5.1872e-01, -1.0271e-01],
        [ 1.6678e+00,  7.7402e-01, -2.1551e+00]])


In [7]:
#torch.Size返回值是tuple类型, 所以它支持tuple类型的所有操作.
print(x.size())

torch.Size([5, 3])


张量加法

In [8]:
#加法
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

#存储到result中
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0199, -0.5166,  0.6921],
        [ 0.5889,  1.5345,  3.7575],
        [ 0.7733, -0.2731,  0.4068],
        [ 0.9219,  0.1965,  0.8221],
        [ 1.6803,  0.9355, -1.1872]])
tensor([[ 0.0199, -0.5166,  0.6921],
        [ 0.5889,  1.5345,  3.7575],
        [ 0.7733, -0.2731,  0.4068],
        [ 0.9219,  0.1965,  0.8221],
        [ 1.6803,  0.9355, -1.1872]])
tensor([[ 0.0199, -0.5166,  0.6921],
        [ 0.5889,  1.5345,  3.7575],
        [ 0.7733, -0.2731,  0.4068],
        [ 0.9219,  0.1965,  0.8221],
        [ 1.6803,  0.9355, -1.1872]])


In [9]:
#替换
# adds x to y
y.add_(x)
print(y)
#任何以_结尾的操作都会用结果替换原变量，例如x.copy_(y)，x.t_()，都会改变x

tensor([[ 0.0199, -0.5166,  0.6921],
        [ 0.5889,  1.5345,  3.7575],
        [ 0.7733, -0.2731,  0.4068],
        [ 0.9219,  0.1965,  0.8221],
        [ 1.6803,  0.9355, -1.1872]])


张量维度

In [10]:
#张量索引
print(x[:, 1])

tensor([-1.2667,  0.5893, -1.0448, -0.5187,  0.7740])


In [11]:
#改变维度
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1：从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
#读取张量元素值
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.1211])
-2.121086835861206


numpy与tensor互转

In [13]:
#tensor转numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#观察a和b的值如何转变
a.add_(1)
print(a)
print(b)
#共用同一块内存空间

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:
#numpy转tensor
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
#观察a和b的值如何转变
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


移动tensor

In [15]:
#cpu和gpu互相转换
a = torch.ones(2,3)
print(a.type())
print(a)
if torch.cuda.is_available():
    b = a.cuda()
    print(b.type())
    print(b)
    
    print(b.cpu())
    print(b.cpu().type())
    
else:
    print("无可用的cuda")

torch.FloatTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.cuda.FloatTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


In [16]:
#,to移动到任何设备
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改
else:
    print("无可用的cuda")

tensor([-1.1211], device='cuda:0')
tensor([-1.1211], dtype=torch.float64)
